# Generated by Django 3.2.9 on 2021-11-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appConcesionarioDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateField()),
                ('caballosPotencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anyoDeCreacion', models.IntegerField()),
                ('fundador', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='habilidades',
        ),
        migrations.RenameModel(
            old_name='Habilidad',
            new_name='Categoria',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.AddField(
            model_name='coche',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appConcesionarioDjango.categoria'),
        ),
        migrations.AddField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appConcesionarioDjango.marca'),
        ),
    ]
