# Generated by Django 3.2.9 on 2021-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appConcesionarioDjango', '0004_marca_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='info',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
