# Generated by Django 3.2.9 on 2021-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appConcesionarioDjango', '0005_alter_marca_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='info',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
