# Generated by Django 3.2.9 on 2021-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appConcesionarioDjango', '0006_categoria_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='info',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
