# Generated by Django 3.2.9 on 2021-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appConcesionarioDjango', '0007_coche_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('info', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='coche',
            name='Combustibles',
            field=models.ManyToManyField(to='appConcesionarioDjango.Combustible'),
        ),
    ]
