# Generated by Django 3.2.9 on 2022-01-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appConcesionarioDjango', '0009_auto_20220110_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fecha',
        ),
    ]
